version: '3.4'

services:
  bookcycle:
    image: bookcycle
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bookcycle
      - MYSQL_USER=bookcycle
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80  #localhost:8001 for db interface
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306